
NUM_TAGS = 5
RECENT_DIRS_LIMIT = 5
DEFAULT_SLIDESHOW_DURATION = 3.0
SUPPORTED_IMAGE_FORMATS = ('.png', '.jpg', '.jpeg', '.bmp', '.gif', '.tif', '.tiff')
FILENAME_LABEL_HEIGHT = 32
WINDOW_MARGIN = 20
AVAILABLE_HEIGHT_OFFSET = 52
